spring.application.name=NoteTakingBackend
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mysql
spring.datasource.username=root
spring.datasource.password=Kirti@90150
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true